<? if (isset($_COOKIE["usertype"])){

	
    include("_main.header.logged.in.php");	
	
			  	  

	} else {
 
		 
	include("_main.header.php");		  
			  

	}?>




<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
</head>

<body background-color="#FFFFFF">



<?PHP
include("dbase.php");

include("settings.php");

?>



<style>
	
	.body{
        font-family:Arial, Helvetica, sans-serif;
		color:#fff;
		background-color:#000 !important;
		text-align: left;
		margin-top: 60px;
		margin-left: 25px;
		margin-right: 25px;
		margin-bottom: 15px;
		padding-bottom: 25px;
		padding-top: 35px;
		padding-left: 125px;
		padding-right: 125px;
		font-size:14px;
		border-radius:7px;
		
	}
	
	
	
.body a:link { 
	font-family:Arial, Helvetica, sans-serif;
	color:#830002 !important;
	font-size: 14px;
	
	}	
</style>	
	
	
	
	
	
	
	
	
	
<div class="body">

	
<h2>TERMS of SERVICE</h2>		
			
				
		<br>				
	

<h2>Adults only.</h2>
<p>We have placed this detail over and above all of our other terms because it is the most important (although it is  also referenced below). Please note that the your-domain.com platform is only open to consenting adults looking to  express themselves in the form of streaming video and messaging. We have zero tolerance for any minors on the  your-domain.com platform, whether such individuals are actually minors or pretending to be minors perhaps in a  misguided attempt at role-play. Moreover, we have zero tolerance for any image of any minor being uploaded to our  platform for any reason. Please be advised that we reserve the right to and do report each and every suspected minor  to the National Center for Missing and Exploited Children and any and all other law enforcement agencies we feel  appropriate. If you believe that a minor is using the site, we request and encourage members to report each and  every user he or she encounters which he or she believes or suspects to be under the age of 18. All reports  are reviewed within minutes (if not seconds) of being received. If you are a minor, you must immediately leave this site  now. You are not legally permitted on your-domain for any reason, and if we find you on this site, we will report you  to law enforcement as noted above. We will not reactivate you for any reason ever.<br>
  <br>
  With respect to all other matters, we have attempted to keep our rules to a minimum only imposing those we feel are  necessary for the safety of our users and the continued operation of your-domain.com. </p>
<h2>Introduction</h2>
<p>When you sign up for or otherwise use any service within the  your-domain.com  website (collectively, the &ldquo;<strong>Site</strong>&rdquo;  &ldquo;<strong>we</strong>&rdquo;  &ldquo;<strong>our</strong>&rdquo; &ldquo;<strong>us</strong>&rdquo; or other  appropriate first-person terms as appropriate), all of which services are hereinafter referred to  collectively as the &ldquo;<strong>Service</strong>,&rdquo; you agree to all of  the Terms and Conditions of this Agreement. Please read the following Terms and Conditions carefully, as they form  the agreement between you, as the Site user (referred to in this Agreement as  &ldquo;<strong>User</strong>&rdquo; &ldquo;<strong>you</strong>&rdquo;  &ldquo;<strong>your</strong>&rdquo; or other appropriate second-person terms),  and the Site (such agreement is referred to herein as the  &ldquo;<strong>Agreement</strong>&rdquo;). IF YOU DO NOT AGREE TO THESE TERMS AND CONDITIONS, YOU MAY NOT USE THE SERVICE, AND  SHOULD NOT PROCEED TO REGISTER OR OTHERWISE USE THE SERVICE. BY USING THE SERVICE, YOU ARE DEMONSTRATING YOUR  WILLINGNESS TO BE BOUND BY THIS AGREEMENT, INCLUDING ANY AMENDMENTS MADE FROM TIME TO TIME.</p>
<h2>Agreement</h2>
<ol>
  <li>Right to Use. Your right to use the Service is subject to any  limitations, conditions and restrictions established by us from time to time, in our sole discretion. We may  alter, suspend or discontinue any aspect of the Service or the Site at any time, including the availability of  any Service feature, database or content. We may also impose limits on certain features and aspects of the  Service or restrict your access to all or part of the Service without notice or liability. </li>
  <li>THIS SERVICE IS FOR ADULTS ONLY! You represent, warrant and  covenant that you are at least 18 years old or the age of majority in your jurisdiction, whichever is older (the  &ldquo;<strong>Age of Majority</strong>&rdquo;). The Site and Service are intended for adults only. By using the Site and  Service you agree that you have reached the Age of Majority. We reserve the right to terminate your account if  we, in our sole and absolute discretion, believe you are in violation of this requirement. We additionally reserve  the right to terminate your account and report you to the proper authorities in the event that we suspect, in  our sole and absolute discretion, that someone who is not the Age of Majority has used your account. </li>
  <li>WE HAVE A ZERO TOLERANCE POLICY FOR CHILD PORNOGRAPHY AND A ZERO TOLERANCE  POLICY REGARDING PEDOPHILES, PEDERASTS OR ANY PEDOPHILIC, PEDERASTIC, OR SIMILAR RELATED ACTIVITY.
    <ol type="a">
      <li>All depictions of any persons on the Site are provided under an obligation of the producer thereof to  upload or stream videos or images portraying persons over the age of 18 as of the date of the  production of the depiction. We undertake great measures to ensure that no underage models appear in any  video or image on the Site. We report all images or videos of minors to law enforcement, including the National  Center for Missing and Exploited Children (&ldquo;NCMEC&rdquo;) regardless of the state of dress of such minor or  the purported purpose for posting the video or pic. We will not contact you prior to reporting such images. We will simply  terminate your account and provide the suspect images and all information to NCMEC. DO NOT UPLOAD OR  STREAM ANY IMAGES OF ANY MINOR FOR ANY REASON. </li>
      <li>If you are seeking any form of child pornography (including so-called &ldquo;virtual&rdquo; child pornography), you must  exit the Site immediately. We do not provide this kind of material and we do not tolerate those who  provide this kind of material, nor do we tolerate consumers of such material. </li>
      <li>In order to further our zero-tolerance policy, you agree to report any images which you have reason to  believe depict minors on the Site by clicking the &ldquo;Support&rdquo; link found at the bottom of each page on the Site.  Include with your report any appropriate evidence, including the date and time of identification. All  reports will be investigated and the appropriate action will be taken based upon our reasonable ability  to verify the evidence provided. </li>
      <li>We unreservedly cooperate with any law-enforcement agency investigating child pornography. If you  suspect other outside websites are participating in unlawful activities involving minors, please report  them to asacp.org. </li>
    </ol>
  </li>
  <li><span id="code_of_conduct">Code of Conduct</span>. You agree to use the Service in accordance  with our Code of Conduct</a>, below:
    <ol type="a">
      <li>The Site provides access to an online service comprising information and materials created and posted,  uploaded, or streamed by you and other users of the Site and/or Service (each a  &ldquo;<strong>Independent Broadcaster</strong>&rdquo;). </li>
      <li>You are solely responsible for any information that you post, display or transmit through the Site and/or  Service. You agree to keep all information contained on or provided through the Site and/or Service as  private and confidential, and agree not give such information to anyone without the permission of the  person who provided it to you; </li>
      <li>You are aware that the Service contains explicit adult-oriented materials, provided only by and to  consenting users who are at least the Age of Majority; </li>
      <li>In the event that you request, upload, stream and/or share any image(s) of any minor, as mentioned  above, we will not contact you. We will simply terminate your account and report you to NCMEC and any  and all law enforcement that we, in our sole and exclusive discretion, determine appropriate; </li>
      <li>You will not use the Service to engage in any form of harassment or offensive behavior, including, but  not limited to, the posting or sharing of any message, picture or recording, which contains may be  libelous, slanderous, harassing, abusive or contain defamatory statements; or racist, obscene, offensive or  other language which is not in accordance with your local laws and community standards; </li>
      <li>Independent Broadcasters and other users are allowed to freely interact with other users or Independent  Broadcasters on the Site, or they may choose to block other Independent Broadcasters or users from communicating  with them, and it is completely up to each Independent Broadcaster or user to choose who they talk to on  the Site. Independent Broadcasters and users are free to ignore anyone and may ban anyone from communicating with  them; </li>
      <li>You will not post any message, picture or recording, or use the Service in any way that:
        <ol type="i">
          <li>Violates, plagiarizes or infringes upon the rights of any third party, including, but not  limited to, any copyright or trademark law, privacy or other personal or proprietary rights, or </li>
          <li>Is fraudulent or otherwise constitutes unlawful conduct in connection with your use of the  Service, or violates any law. </li>
        </ol>
      </li>
      <li>You will not use the Service to distribute, promote or otherwise publish any material that  constitutes or contains solicitation of funds, advertising or solicitation for goods or services; </li>
      <li>Your access to the Service is for your own personal use only. You may not allow others to use the Service  using your account(s) and you may not transfer your account(s) to any other person; </li>
      <li>You will not use the Service to infringe on any privacy right, property right, or other civil right of  any person; and </li>
      <li>You will not publish or forward any chain letters, advertisements, spam, or any similar commercial message through the  Service. </li>
    </ol>
  </li>
  <li>Illegal and Prohibited Conduct. In addition to the above Code of Conduct Independent Broadcasters are prohibited from doing any of the following:
    <ol type="a">
      <li>There can be no minors, children, babies or unauthorized persons on camera or in the same room. In the  event a minor appears on camera, even for a second, we will immediately report you to NCMEC and any and all law  enforcement that we consider appropriate in our sole and absolute discretion. </li>
      <li>Bestiality, or animals/pets on camera in a sexual or provocative context, or illegal drugs (or drugs  that may be perceived as illegal in certain locations, such as medicinal marijuana) are strictly prohibited. </li>
      <li>Sleeping on camera (whether real or acting/pretending) is not permitted.</li>
      <li>Overly large sex toys or animal-shaped sex toys may not be used on camera, and objects may not be used  as sex toys unless they are normally marketed and sold for that purpose. Email <a href="mailto:support@your-domain.com">support@your-domain.com</a> for authorization  and provide a detailed proposal to incorporate any type of mechanical device, tool, &ldquo;sex machine&rdquo; or  other unusual equipment into your performance (whether controlled by you or controlled remotely by users of the Site).  We may require you to sign a waiver and release of liability in order to use  certain devices on the Site, and any authorization or permission we give to you may be revoked by us at any time  and for any reason, without notice, in our sole and absolute discretion. </li>
      <li>Performing while intoxicated, whether from alcohol or drugs (prescription, legal or illegal), is  strictly prohibited. </li>
      <li>Incest (sexual relations involving family members) is not allowed.</li>
      <li>Excessively degrading dialog or verbal abuse is not allowed.</li>
      <li>Displays or reference to menstruation, vomit, feces, or urine are not permitted.</li>
      <li>"Bukakke" scenes are not allowed.</li>
      <li>"Goatse" displays are prohibited.</li>
      <li>Illegal or unsafe activities of any kind, including violence, blood, torture, pain, erotic asphyxiation, fisting,  rape themes, or any actions associated with bringing harm to you, in any way, are prohibited. </li>
      <li>Independent Broadcasters may not broadcast from a public place, or from a studio or set that creates the  impression that the Independent Broadcaster is in a public place. </li>
      <li>Independent Broadcasters are prohibited from broadcasting outdoors unless the broadcast is done from  private property, with the property owner&rsquo;s consent, and in an area that is not visible from any  neighboring property. </li>
      <li>An Independent Broadcaster may not discuss or arrange prostitution or escort services.</li>
      <li>Any action that may be deemed obscene in your community is prohibited.</li>
      <li>Independent Broadcasters may exchange information with users of the Site, including contact information,  but Independent Broadcasters MAY NOT use users' information to provide webcam shows or receive payments  outside of the Site. If an Independent Broadcaster sells something to a user (such as the Independent  Broadcaster's underwear) or enters into any other transaction with a user of the Site, the sale must  be completed in exchange for Virtual Money (defined below). </li>
      <li>Independent Broadcasters are not allowed to advertise commercial websites that offer live webcam  streams, under any circumstances; but they are allowed to mention their own personal profiles, homepages  and wish lists. </li>
      <li>Independent Broadcasters are not allowed to ask for other users' account information, or to log on to  the Site using any account that does not belong exclusively to that Independent Broadcaster. </li>
      <li>Independent Broadcasters are prohibited from making any statements, written or verbal, or cause or  encourage others to make any statements, written or verbal, which defame, disparage, or in any way  criticize the Site or Service. </li>
    </ol>
  </li>
  <p>This list is not exclusive, and we may, at any time, prohibit any activity that we determine, in our  sole and absolute discretion, to be inappropriate. We reserve the right to terminate or suspend your access to  all or part of the Service at any time, with or without notice, for engaging in any inappropriate activity. </p>
  <li>Privacy and Use of Information. Your personal information will  not be disclosed to any third party, except as set forth in our Privacy Policy</a>. </li>
  <li>Content Posted on the Site.
    <ol type="a">
      <li>By agreeing to the Terms and Conditions of this Agreement, you   represent and warrant that any images or video you  upload to the Site do not in any way infringe on any third party&rsquo;s   intellectual property or other rights. The  Site hereby asserts immunity with respect to all content provided by   Independent Broadcasters, members or other third parties, as  provided by law, including, but not limited to, under the <em>Communications Decency Act</em>. Users and others  are prohibited from uploading, sharing or in any way sharing or describing to anyone on or through the  Site/Service any images or matters which, in our sole opinion, might be illegal or offensive, including,  but not limited to, any content involving bestiality, urination or other bodily excretions, defamatory  material or otherwise obscene material or any conduct that violates the prohibitions set forth under our Code of Conduct or any part of this Agreement. You may not use the Service or the  Site to solicit any information that might be used for unlawful purposes or encourages unlawful  activities. </li>
      <li>We do not claim any ownership rights in the text, files, images, photos, video, sounds, musical works,  works of authorship, applications, or any other materials (collectively, the  &ldquo;<strong>Materials</strong>&rdquo;) that you transmit, submit, display or publish  (&ldquo;post&rdquo;) on the Site or through or in connection with the Service. After posting the Materials on the Site  or through or in connection with the Service, you continue to retain any such rights that you may have in  such Materials, subject to the license granted herein. By posting the Materials on the Site or through or  in connection with the Service, you hereby grant to the Site a non-exclusive, fully-paid and  royalty-free, sub-licensable, and worldwide license to use, modify, delete from, add to, publicly  perform, publicly display, reproduce, and distribute the Material, including, without limitation,  distributing all or part of the Materials, in any media formats and through any media channels. In  addition to the foregoing license, you hereby authorize us to send takedown demands, pursuant to the <em>United States&rsquo; Digital Millennium Copyright Act</em> (&ldquo;DMCA&rdquo;), to any service provider hosting  reproductions of the Materials that have been taken from the Site (e.g., a video clip bearing our  watermark). </li>
      <li>You may not use the Site or Service for commercial purposes, including, but not limited to, marketing,  advertising of goods or services, any investment opportunities, contests, or similar activities.  Additionally, we reserve the right, in our sole discretion, to immediately suspend your  account, seek injunctive relief, seek civil redress and/or report any conduct that violates  these Terms and Conditions to any and all law enforcement agencies that may have jurisdiction over the matter. In  the event any actions or proceedings are brought against the Site as a result of any content you have shared  in, or as a result of you engaging in any prohibited activities, you agree to indemnify and hold the  Site harmless with respect to all costs and expenses, including, but not limited to, attorneys&rsquo; fees  that the Site may incur as a consequence of your posting of such content or engaging in such prohibited  activities. </li>
    </ol>
  </li>
  <li>Members&rsquo; Obligations Under <em>18 U.S.C. §2257</em>.   You should be  aware that, pursuant to United States federal law, any visual depictions   that you post, share or perform on the Site or through the Service   which  portray "actual sexually explicit conduct", "depictions of the genitals   or pubic area", or "simulated sexually  explicit activity", as those terms are defined in <em>18 U.S.C. §2256(2)(A)(i)-(iv) and §2257A</em>, require that you  maintain the records listed under <em>18 U.S.C. §2257</em>, and any such postings must contain a &ldquo;18 U.S.C. §2257  Record-Keeping Requirements Compliance Statement.&rdquo; Your failure to comply with the provisions of 18 U.S.C. §2257  may make you subject to criminal and civil prosecution for the violation of federal law. </li>
  <li>Use of Information on Service. You acknowledge and agree that:
    <ol type="a">
      <li>We cannot ensure the security or privacy of information you provide through the Internet or otherwise.  You release us from any and all liability in connection with the breach of the security of such  information and/or messages and with respect to the use of such information by other parties; </li>
      <li>We are not responsible for, and cannot control, the use of any information, by anyone, that you provide  to other parties through the Service. Use caution in deciding what personal information you  share with others through the Service. </li>
      <li>We cannot assume any responsibility for the content of any message sent by any user on the Service. You  release us from any and all liability in connection with the content(s) of any communication(s) you  may receive from other users. </li>
      <li>You will not bring legal action against the Site or any of its employees, officers or  agents for any damages of any kind, under any theory, as a consequence of using the Service. </li>
      <li>Any and all images uploaded to the Site or through the Service become licensed property of the Site and may be  used by the Site, without any restriction(s), as marketing materials free of any restrictions. By accepting this Agreement and  its Terms and Conditions you specifically authorize us to use any images you upload to the Site/Service  for marketing the Site and Service, in our sole discretion. </li>
      <li>You may not use the Service or Site for any unlawful purpose. We may refuse to grant you or discontinue your use  of any username, for whatever reason, including, for example, if the username you have chosen  impersonates or suggests you are someone else, is protected by trademark or proprietary law, or is vulgar or otherwise  offensive, as determined by us in our sole discretion. </li>
    </ol>
  </li>
  <li>On- or Off-Site Interactions/Meetings. The Site does not  recommend or condone any form of user interaction between users outside of the Site and, as disclosed elsewhere in this  Agreement, your use of the Site and your interactions through the Site are done at your own risk. Use of the Site to arrange  face-to-face meetings for the purpose of engaging in illegal activity is strictly prohibited and will subject  your account to immediate termination. If you elect to legally interact with any user of the Service  outside of the Site, you do so at your own risk, and you acknowledge and agree that we are not responsible for  any consequences of your election to interact with anyone, whether in person or otherwise, outside of the Site.
    <p>You should, at a minimum, consider the following precautions if meeting or corresponding with anyone on any  social networking site:</p>
    <ol type="a">
      <li>Anyone who is able to commit identity theft can also falsify a user profile.</li>
      <li>There is no substitute for acting with caution when communicating with any stranger who wants to meet  you. </li>
      <li>Never include your last name, email address, home address, phone number, place of work, or any other  identifying information in your user profile or initial email messages. Immediately stop communicating with anyone  who pressures you for personal or financial information or attempts in any way to trick you into  revealing it. </li>
      <li>If you choose to have a face-to-face meeting with another user, always tell someone in your family or   a friend where you are going and when you will return. Never agree to be picked up at your home. Always  provide your own transportation to and from the meeting, and meet in a public place with many  people around. </li>
      <li>All the money and gifts you send to other users, whether directly or indirectly, through the Site or outside  of the Site, is done at your own risk. We will not intervene or become involved in any dispute between users. </li>
    </ol>
  </li>
  <li>Your Representations and Warranties. By using the Service, you  thereby affirmatively acknowledge, represent, and warrant the truth and accuracy of each of the statements below:
    <ol type="a">
      <li>You are not prohibited by law from using the Service and that you have the legal right, authority and capacity  to enter into this Agreement and to abide by all of its Terms and Conditions, as may be amended from time to time. </li>
      <li>You are familiar with the laws in your area that may affect your legal right to access erotica or  adult-oriented material, you have the legal right to access such material, and the Site has the legal  right to transmit such material to you in your location. </li>
      <li>You understand that by using the Service you will be exposed to visual images, verbal descriptions, audio/sounds  and other features and/or products of a sexually-oriented, openly erotic nature which may include graphic  visual depictions and descriptions of nudity and sexual activity, and you are voluntarily choosing to proceed  with your use of the Service because you want to view, read, hear or order such content, materials or products  and because you enjoy such content, materials or products, available on the Site or through the Service for your  own personal enjoyment, information and/or education. </li>
      <li>Your choice to use the Service is a manifestation of your interest in sexual matters, which you believe  is healthy and normal and which, in your experience, is generally shared by the average adult in your community. </li>
      <li>You are familiar with the standards in your community regarding acceptance of sexually oriented materials,  and the materials you expect to encounter through use of the Service are within your community standards. </li>
      <li>In your judgment, the average adult in your community (i) accepts the consumption of adult-oriented materials  by willing adults in circumstances such as those under which the Service is provided (i.e., offering reasonable  insulation from such materials for minors and unwilling adults); and (ii) would not find such materials to  appeal to a prurient interest or to be patently offensive. </li>
      <li>It is your desire to share or to invite others to share your own private and personal behaviors and to comment,  rate, criticize, organize and recommend based on what you are exposed to by your use of the Service, while  inviting others to do the same. </li>
      <li>You have not notified any governmental agency, including the U.S. Postal Service, that you do not wish  to receive sexually oriented material. </li>
      <li>The Site provides access to an online service comprising information and materials created and posted,  uploaded, or streamed by you and other users (each an  "<strong>Independent Broadcaster</strong>"). </li>
      <li>Video and images on the Site that are available for viewing (the &ldquo;<strong>Content</strong>&rdquo;) are stored on or streamed through our servers at the direction of  our users. </li>
      <li>Any modification of the Content that is uploaded or streamed by our users, such as the addition of a watermark,  is done via an automated process. As a result, because the Independent Broadcaster is aware that such modifications take  place automatically upon transmission of the Content, the Independent Broadcaster shall be deemed the party responsible  for such automatic modification and shall be considered the &ldquo;author&rdquo; of such automatically modified Content.  The Site is not responsible for modifications that occur to Content as part of its automatic transmission process. </li>
      <li>Any review of uploaded or streamed Content that may be performed by the Site before or after making such  Content available to the public is cursory and only intended to identify immediately or patently obvious  violations of this Agreement. Accordingly, and despite any such gatekeeping, the Independent Broadcaster uploading  or streaming any Content shall be deemed the party at whose direction that Content is available to others  through use of the Service. </li>
      <li>The Site has never directed, and never will direct, its users to upload or stream Content that infringes  upon any right of a third party. Uploading or streaming Content that infringes on third-party rights  constitutes a direct and material violation of this Agreement and will subject the uploading or streaming  Indepdendent Broadcaster&rsquo;s account to suspension and/or termination where appropriate. </li>
      <li>The Site has no right or ability to control the activities of Independent Broadcaster who create, post, upload, or  stream Content through the Site or Service. In the event that a Independent Broadcaster infringes upon a third party&rsquo;s  rights by creating, posting, uploading, or streaming infringing Content, that Independent Broadcaster is the sole  responsible party for such infringement, and the Site has no control over such activity and no liability  therefor. </li>
      <li>The Site appropriately presumes that the Independent Broadcaster uploading or streaming any Content is the holder of  all exclusive rights to that Content, except where the Content itself bears some obvious indication to  the contrary, such as a visible proprietary mark identifying a person or entity other than the Independent Broadcaster  as the exclusive rights holder. </li>
      <li>Where Content contains no obvious proprietary marking that indicates an exclusive owner different from the  Independent Broadcaster, the Site shall not be deemed to have actual or imputed knowledge that such Content infringes  upon any third party&rsquo;s rights. </li>
      <li>Apart from identifying an obvious proprietary marking in any Content that indicates an exclusive owner,  the Site has no other ability to determine whether the rights appurtenant to a particular piece of Content  may belong to a party other than the uploading or streaming Independent Broadcaster. As the Site&rsquo;s only other means  of identifying Content that may infringe upon a third party&rsquo;s rights, the Site relies entirely on properly  presented notifications from third parties claiming that their rights have been violated. </li>
    </ol>
  </li>
  <li>Notice of Intellectual Property Infringement. The Site respects  the intellectual property of others, and we ask our community members and others to do the same. We voluntarily  observe and comply with the DMCA. IT IS your-domain&rsquo;S POLICY TO TERMINATE ACCOUNTS OF REPEAT COPYRIGHT INFRINGERS  WHEN APPROPRIATE. If you believe that your work has been copied through use of the Service in a way that constitutes  copyright infringement, or your intellectual property rights have been otherwise violated, please provide the Service&rsquo;s  Designated Copyright Agent the following information:
    <ol type="a">
      <li>an electronic or physical signature of the person authorized to act on behalf of the owner of the  copyright or other intellectual property interest; </li>
      <li>description of the copyrighted work or other intellectual property that you claim has been infringed; </li>
      <li>a description of where on the Service the material that you claim is infringing is located;</li>
      <li>your address, telephone number, and email address;</li>
      <li>a statement by you that you have a good faith belief that the disputed use is not authorized by the  copyright owner, its agent, or the law; and </li>
      <li>a statement by you made under penalty of perjury that the information in your Notice is accurate and that  you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual  property owner's behalf. </li>
    </ol>
  </li>
  <p>email your Notice of Claimed Infringement to us via our contact page.</p>

    Email: Notice[at]DMCANotice[dot]com </blockquote>
  <p>Do not send other inquires or information (other than Notices of Infringement) to our Designated Agent. Any other  inquiries should be sent to <a href="mailto:support@your-domain.com">support@your-domain.com</a>.</p>
  <li>Virtual Money. The Service may, but is not obligated to, include  a virtual, in-app currency (&ldquo;<strong>Virtual Money</strong>&rdquo;)  including but not limited to coins, cash, tokens or points, that may be purchased from us for &ldquo;real-world&rdquo; money  if you are a legal adult in your country of residence. Other than a limited, personal, revocable, non-transferable,  non-sublicenseable license to use the Virtual Money as part of the Service, you have no right or title in or to any  such Virtual Money appearing or originating in the Service, or any other attributes associated with use of the  Service or stored within the Service. We have the absolute right to manage, regulate, control, modify and/or  eliminate such Virtual Money in our sole discretion, and we shall have no liability to you or anyone for the  exercise of such rights. Transfers of Virtual Money are strictly prohibited except where explicitly authorized  within the Service. Except as expressly provided in this Agreement, you may not sell any Virtual Money for  &ldquo;real-world&rdquo; money or otherwise exchange such items for value. Any attempt to exchange Virtual Money for actual  currency, other than by following the process established by your-domain, is in violation of this Agreement and  may result in a lifetime ban from the Site and possible legal action. All Virtual Money that has not been purchased  directly by You (e.g., tips from other users, referral commissions, etc.) is forfeited if your account is terminated  or suspended for any reason in our sole and absolute discretion, or if we discontinue providing the Service. </li>
  <li>Tipping. The Site may, but is not obligated to, permit tipping  of age-verified Independent Broadcasters through the Service. To the extent that we decide to allow tipping, you acknowledge  and agree that:

  </li>
  <li>Pics and Video Purchases. The Site may, but is not obligated to,  permit users to post Materials that can only be accessed after payment of a specified amount of Virtual Money  (&ldquo;<strong>Paid Content</strong>&rdquo;). If you post any Paid Content,  you represent and warrant that (i) the Paid Content you post complies in all respects with the terms of this  Agreement; and (ii) you have all rights and permissions necessary to post such Paid Content and to permit users  to access the same in exchange for payment. We have the absolute right to remove any Paid Content, in whole or  in part, for any or no reason at all. In the event any Paid Content you posted results in chargebacks or refund  requests from users who have purchased such Paid Content, we reserve the right to assess a chargeback fee to your  account and/or suspend your ability to post Paid Content. By purchasing or accessing any Paid Content, you thereby  demonstrate your express acknowledgement and agreement that (i) the Site is not the creator or source of such Paid  Content; (ii) the user posting Paid Content is solely responsible for any claims or liabilities associated with,  arising from, or in any way relating to such Paid Content posted by that user; (iii) your purchase or use of any  Paid Content is solely at your own risk; (iv) the Site has no responsibility for viewing or screening any Paid  Content; and (v) you forever release the Site, its affiliates, successors, assigns, officers, employees, agents,  directors, shareholders and attorneys from any and all claims and liabilities associated with, arising from, or  in any way relating to Paid Content. </li>
  <li>Fan Clubs. The Site may, but is not obligated to, permit certain  users to create and administer their own fan club on the Site. Eligible users may be permitted to set a monthly  fee that other Site users must pay, via Virtual Money, to be members of the performing users&rsquo; fan club, and the  Site may, but is not obligated to, credit a portion of such payment to the performing user&rsquo;s account. We reserve  the right to rescind any user&rsquo;s permission to maintain a fan club for any or no reason at all. In the event that  members of your fan club request a refund from us, or institute a chargeback with our payment processor, we reserve  the right to assess a chargeback fee to your account and/or suspend your ability to maintain a fan club on the Site. </li>
  <li>Contests. From time to time we may offer the opportunity for you  to participate in contests that shall be administered through the Site and Service. While the general rules that  apply to all contests are presented below, the particular details of any currently running contest can be found on  our <a href="http://your-domain.com/contest/details/"> contest rules page</a>.
    <ol type="a">
      <li>Entry and Eligibility. Unless otherwise noted in the rules  applicable to a specific contest, entry will be automatic for any user of the Site who maintains an  age-verified account with the Service. All registered Site users shall be eligible to participate in  any contest, provided that they have complied with these Terms and Conditions, and that such contest is  not prohibited in their home jurisdiction. All contests shall be void where prohibited. You may  expressly opt out of any contest by sending an email to <a href="mailto:support@your-domain.com">support@your-domain.com</a>. </li>
      <li>Contest Periods. Each contest shall have a posted  beginning date. An end date may be provided as soon as practicable after determination, but is not  required. Each contest shall run for a period of time that begins on the posted beginning date and  ends on the posted end date, if any. </li>
      <li>Conduct. By participating in any contest run by the Site,  you demonstrate your agreement to comply with and be bound by our decisions regarding such contest, which  shall be final and binding in all respects. We reserve the right in our sole discretion to disqualify  any entrant in any contest who we deem to be: (i) tampering or attempting to tamper with the entry process  or the operation of a contest; (ii) violating these Terms or any contest rules; or (iii) acting in an  unsportsmanlike or disruptive manner, or with the intent to annoy, abuse, threaten or harass any other person.  Any false information provided within the context of the contest by any entrant concerning identity, postal  address, or non-compliance with any contest rules may result in the immediate disqualification of an entrant  from any contest. We further reserve the right to disqualify any entry that we believe, in our sole discretion,  infringes upon any third-party right, violates any law or otherwise does not comply with these Terms or  any contest rule. </li>
      <li>Prizes. The rules of each contest shall set forth the  prizes to be awarded. In the event that there are multiple prizes offered for a particular contest,  but there are an insufficient number of eligible entrants in that contest, not all prizes will be awarded.  If a winner is not able for whatever reason to accept his or her prize, we reserve the right to not award  the prize or to award the prize to another entrant. </li>
      <li>Claiming Cash Prizes. In the event that cash prizes are  awarded for any contest, no potential prize winner shall be entitled to receive payment, nor shall the Site  be liable for any such payment, unless and until the total amount of unclaimed funds associated with your  account exceeds Fifty Dollars (USD $50.00). In order to receive cash prizes, potential prize winners will  be required to complete a claim form, which will include submission of that person&rsquo;s legal name, a copy of  their government-issued photo identification, mailing address, birth date, telephone number, social security  number and a selection of a preferred payment method. Claim forms are processed once per month, and claimed  cash prizes will be sent using each potential prize winner&rsquo;s chosen payment method on or before the seventh  day of the month following receipt of the processed claim form. In addition, depending on the amount of  prize winnings claimed, potential prize winners may be required to sign, notarize and return an affidavit  or declaration of eligibility, a liability release, IRS Form W-9 and/or provide any additional information  that may be required by the Site. Failure to provide any requested information may result in disqualification  and selection of an alternate winner. </li>
      <li>No Recourse to Judicial or Other Procedures. To the extent  permitted by law, the rights to litigate, to seek injunctive relief, or to any other recourse to judicial  or any other procedure in case of disputes or claims resulting from or in connection with any contest are  hereby excluded, and you expressly waive any and all such rights. </li>
      <li>General Conditions. All contests are governed by the laws  of the State of Florida. All federal, state and local laws and regulations apply. By participating in any  contest, you agree to be bound by the contest rules and by our decisions, which are final and binding on  all matters pertaining to that contest. We are not responsible for any typographical or other error in  the administration of any contest or in the announcement of any prizes. </li>
    </ol>
  </li>
  <li>Monitoring of Information. We reserve the right, but have no  obligation, to monitor any and all messages and chats that take place through the Site. We are not responsible  for any offensive or obscene Material(s) that may be in anyway transmitted by any users (including unauthorized  users, including the possibility of &ldquo;hackers&rdquo;). As noted above, we are also not responsible under any circumstances  for the use of any personal information, by anyone, that you in anyway transmit through the Service. </li>
  <li>Termination of Access to the Service. We may, in our sole discretion,  terminate or suspend your access to all or part of the Service at any time, with or without notice, for any reason  or no reason at all, including, without limitation, breach of this Agreement. Without limiting the generality of  the foregoing, any fraudulent, abusive, or otherwise illegal activity may be grounds for termination of your access  to all or part of the Service at our sole discretion, and we reserve the right to refer any such activity to any  appropriate law enforcement agencies. </li>
  <li>Proprietary Information. The Service contains information that  is proprietary to us and/or users of the Service. We assert full copyright protection in the Service, including  all of the design and code embodied therein. Any information shared or posted by us or by users of the Service  may be protected whether it is identified as proprietary to us or to the user. You agree not to modify, copy or  distribute any such information in any manner whatsoever without having first received the express permission of  the owner of such information. You may not use any automated means to in anyway monitor, "scrape", download,  use or otherwise collect data and/or content from the Site, including, without limitation, robots/bots,  crawlers, or data mining tools. </li>
  <li>No responsibility. We are not responsible for any incidental,  consequential, special, punitive, exemplary, direct or indirect damages of any kind whatsoever, which may arise  out of or relate to your use of the Service, including but not limited to lost revenues, profits, business or  data, or damages resulting from any viruses, worms, &ldquo;Trojan horses&rdquo; or other destructive software or materials,  or communications by you or other users of the Service, or any interruption or suspension of the Service,  regardless of the cause of the interruption or suspension. Any claim against us shall be limited to the amount  you paid, if any, for use of the Service during the previous 12 months. We may discontinue or change  the Service or its availability at any time, and you may stop using the Service at any time. Please see details  regarding Cancellation below. </li>
  <li>Security. Your account is private and may not be used by anyone  else under any circumstances. You are responsible for all usage or activity on the Service by users using your  login and password, including but not limited to use of your login and password by any third party. </li>
  <li>Other Links. The Service may from time to time contain links to  other sites and resources (&ldquo;<strong>External Links</strong>&rdquo;).  We are not responsible for, and have no liability as a result of, the availability of External Links or their  contents. </li>
  <li>No Warranties. The Service is distributed on an &ldquo;as is&rdquo; and &ldquo;as  available&rdquo; basis. We do not warrant that the Service will be uninterrupted or error-free. There may be delays,  omissions, and interruptions in the availability of the Service. WHERE PERMITTED BY LAW, YOU ACKNOWLEDGE THAT  THE SERVICE IS PROVIDED WITHOUT ANY WARRANTIES OF ANY KIND WHATSOEVER, EITHER EXPRESS OR IMPLIED, INCLUDING BUT  NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE; NOR DOES THE SITE  MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES OR AS TO THE ACCURACY OR  RELIABILITY OF ANY INFORMATION OBTAINED THROUGH THE SERVICES OR THAT DEFECTS IN ANY SOFTWARE, HARDWARE OR THE  SERVICES WILL BE CORRECTED. YOU UNDERSTAND AND AGREE THAT ANY USE YOU MAKE OF ANY MATERIAL AND/OR DATA DOWNLOADED  OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS AT YOUR OWN DISCRETION AND RISK, AND THAT YOU WILL BE SOLELY  RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL  AND/OR DATA. We do not represent or endorse the accuracy or reliability of any advice, opinion, statement or other  information displayed, uploaded or distributed through the Service by the Site or any user of the Service or any  other person or entity. You acknowledge that any reliance upon any such opinion, advice, statement or information  shall be at your sole risk. </li>
  <li>Modifications. We may modify this Agreement from time to time.  Notification of changes in this Agreement will be posted on the Service or sent via email, as determined by us in  our sole discretion. If you do not agree to any modifications, you should terminate your use of the Service.  Your continued use of the Service now, or following the posting or receipt of notice of any changes in this  Agreement, will constitute a binding acceptance by you of this Agreement, as modified. </li>
  <li>Nature of Relationship / Disclaimer of Agency. Nothing in this  Agreement is intended by you or the Site to constitute an employment relationship, a joint venture, or collaboration  between you and the Site. You acknowledge that you are in no way an employee or agent of the Site and as such,  you have no authority to act on the Site&rsquo;s behalf or to bind the Site to any obligation or agreement. This  provision also applies to users promoting or making referrals to the Site. </li>
  <li>Disclosure and Other Communication. We reserve the right to send  you email for the purpose of informing you of changes or additions to the Service, or of any related products and  services offered by the Site or its affiliated entities. We reserve the right to disclose information about your  usage of the Service and demographics in ways that do not reveal your personal identity. For a more detailed  description of what information we may disclose, please review our Privacy Policy, incorporated in its entirety into and part of this Agreement by this reference. </li>
  <li>Tax Documents. To the extent you who receive compensation from  the Site (e.g., tips from other users, or referral commissions) and we are required by law or deem it necessary  to provide you with tax documents related to such compensation, by executing this Agreement, YOU HEREBY AGREE  AND CONSENT TO RECEIVE ANY SUCH TAX DOCUMENTS VIA ELECTRONIC MEANS, including via email and/or in Adobe .pdf  format. If you do not consent to, or opt-out of, electronic delivery of form 1099, you will receive a paper  copy via regular U.S. snail mail. This consent is effective immediately for any tax documents we send you in  the future, and will remain in effect until and unless revoked by you in writing. To obtain a paper copy of any  tax document we are required to provide or have provided to you, to revoke your consent to electronic delivery of  tax documents, or to update your address or contact information on file with us, email <a href="mailto:support@your-domain.com">support@your-domain.com</a>. </li>
  <li>Complaints. To resolve or report a complaint regarding the  Service or users of the Service, users should send an email detailing their complaint to <a href="mailto:support@your-domain.com">support@your-domain.com</a>. In appropriate circumstances, we will take  immediate action in order to help resolve the problem. </li>
  <li>Registration. You may become a user of the Service by completing  an online registration form, which must be accepted by the Site. Upon submission of the online registration form,  the Site or its authorized agent will process the application. In connection with completing the online registration  form, you agree to:
    <ol type="a">
      <li>Provide true, accurate, current and complete information about yourself as prompted by the registration  form (&ldquo;<strong>Registration Data</strong>&rdquo;); and  </li>
      <li>Maintain and promptly update the Registration Data to keep it true, accurate, current and complete at all  times while you remain a user of the Service. </li>
    </ol>
  </li>
  <p>You must promptly inform the Site of all changes to the Registration Data, including, but not limited to, changes  in your address, and changes in the credit card information you designated for billing for the Service. If you  provide any information that is untrue, inaccurate, not current or incomplete, or the Site or any of its authorized  agents have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete,  the Site has the right to suspend or terminate your account and refuse your current or future use of the Service  and Site, as well as possibly subjecting you to criminal and civil liability. You are responsible for rejected  payments and any related fees that we incur with respect to your account. Effective October 17, 2015 we no longer  accept payment by check. Any and all checks received by us will be destroyed or returned to you, as we may  determine in our sole discretion. We continue to accept payments by ACH. </p>
  <li>Member Account and Password. As part of the registration process,  you will be issued a unique username and password, which you must provide in order to gain access to the non-public  portions of the Service. You certify that, when asked to choose a username, you will not choose a name that falsely  represents you as somebody else, or a name that may otherwise be in violation of the rights of a third party.  We reserve the right to disallow the use of usernames that we, in our sole discretion, deem inappropriate. We  reserve the right to cancel, at any time, the membership of any user who uses their selected username in violation  of these Terms and Conditions or in any other way we deem inappropriate in our sole discretion. Your membership,  username and password are non-transferable and non-assignable. You represent and warrant that you will not disclose  to any other person your username or password and that you will not provide access to the Service to anyone who  is below the Age of Majority, or who does not willingly wish to view the content on the Site. You are solely  responsible for maintaining the confidentiality of your username and password and are fully responsible for all  activities that occur under your username and password. We will not release your password for security reasons.  You agree to (a) immediately notify the Site of any unauthorized use of your username or password or any other  breach of security, and (b) ensure that you exit from your account at the end of each session. You agree that  you are solely liable and responsible for any unauthorized use of the Service using your account until you notify  the Site by email regarding the unauthorized use or access. Unauthorized access to the Service is illegal and a  breach of this Agreement. You agree to indemnify the Site with respect to all activities conducted through your  account. You may obtain access to your billing records upon reasonable request. </li>
  <li>Promotion of the Site and Service. Registered users of the Service  may be eligible to participate in our affiliate advertising program and potentially earn commissions based on the  number and quality of registered user referred to the Site.
    <ol type="a">
      <li>License to Promotional Items. All registered users of  the Site/Service who are currently in compliance with the terms of this Agreement are hereby granted a  revocable, non-exclusive, non-transferable license to utilize the Site&rsquo;s name, access and download  promotional banners, videos, photographs, other promotional materials, and/or promotional materials  created by you, provided that such materials are approved by the Site in writing  (&ldquo;<strong>Promotional Items</strong>&rdquo;), for use on  site(s) owned by such registered users (&ldquo;<strong>Referral Sites </strong>&rdquo;). The Promotional Items are licensed to eligible registered users for the limited   purposes of advertising, marketing and promoting the Site and Service. Any and all licenses granted to  registered users pursuant to this Agreement shall immediately cease and revert to us  upon the termination or cancellation of this Agreement. You agree not to share any of the Promotional  Items with anyone in any way, which is not in accordance with the terms of this Agreement and applicable  law. You hereby acknowledge and agree that all rights to the Promotional Items belong solely to the Site  and/or the Site&rsquo;s licensor(s). You further acknowledge and agree that any Promotional Item(s) created by  you and approved by the Site are a specially ordered and commissioned &ldquo;work made for hire&rdquo; within the  meaning of the <em>1976 Copyright Act</em> for the good and valuable consideration provided you herein. </li>
      <li>Keywords; Domain Names. Notwithstanding the foregoing  license to use the names of our Site in connection with referring traffic to the Service, you are not,  as a part of this license, permitted to (i) bid on, purchase or otherwise register/use &ldquo;your-domain,&rdquo;  &ldquo;your-domain.com,&rdquo; or any other similar spelling, or use same in connection with the words &ldquo;Official,&rdquo;  &ldquo;Officially&rdquo; or &ldquo;Official Site&rdquo; as keywords or advertising words on any internet search engines, including  without limitation, google.com, bing.com, ask.com, yahoo.com, etc.; use the Site name in association with  any similar or competing website or service; or (ii) register any domain name which incorporates or is a  &ldquo;misspelling&rdquo; or variation of &ldquo;your-domain.&rdquo; You agree that in the event you violate any part of this  section of this Agreement, your account will be immediately terminated, any monies earned but not yet  paid will be forfeited, and that you will cooperate fully in transferring any items forbidden by this  section to the Site as the rightful owner. Subject to the foregoing limitations and pursuant to the  license granted herein, eligible registered users will be permitted to use any website domain name they  choose in connection with promoting the Site and Service, so long as such website domain name(s)  registered does not infringe on our or any third party's intellectual property rights, or defame, insult  or otherwise harass anyone, and does not promote or suggest any illegal activity. </li>
      <li>Restrictions. You are prohibited from using any images,  text, script(s), applications, logos and functional elements appearing on a Referral Sites, to which you  do not have all legal rights, free from any and all encumbrances and third party claims. Further, you  represent and warrant that you will only advertise on services and providers that permit advertisement of  services such as the Site. You understand and agree that if you advertise on any service or provider that  does not permit such advertising, your account will be terminated without notice and without payment or  liability. Furthermore, you acknowledge and agree that we may, at any time, review the contents of any  Referral Site and disapprove of any material thereon that might, in our sole discretion, reflect negatively  upon the Site or the Service. Upon request from us, such material must be immediately removed in order  for you to remain eligible to receive commissions hereunder. </li>
      <li>No Email Marketing. We do not permit promotion of the  Site by email marketing. You acknowledge and agree that any email marketing by you will be grounds for  immediate termination of your account without payment. </li>
      <li>User Referral Link. Each user shall be assigned one or  more unique URLs (each a &ldquo;<strong>User Referral Link </strong>&rdquo;) that must be used when referring new users in order to connect such new users to the existing  user who referred them. Your User Referral Links can be found on the &ldquo;My Profile&rdquo; page under the &ldquo;Share&rdquo;  tab. You acknowledge and agree that we are not obligated to pay any commissions to you for any new user  signups or spending that did not directly result from clicking on your User Referral Links. </li>
      <li>Commissions on User Spending. The Site will compensate  eligible users, subject to the terms of this Agreement in all respects, a commission for certain types of  referrals generated by such eligible users, as set forth in further detail below:
        <ol type="i">
          <li>Definition of Adjusted Gross Receipts. As used herein, &ldquo;<strong>Adjusted Gross Receipts</strong>&rdquo; means gross payments received from a subject  user, less any chargebacks (including amounts paid as a result of credit card abuse or fraud, or  paid to such subject user by us to settle a claim involving the allegation of credit card or other  abuse or fraud) or any uncollectable revenue attributable to the subject user. </li>
          <li>Paying User Referrals. As used herein, a  &ldquo;<strong>Referred User</strong>&rdquo; means an Internet user who creates a new your-domain user account  as a result of clicking an existing user&rsquo;s User Referral Link. Eligible users will receive a  commission equal to 20% of Adjusted Gross Receipts paid by each of their Referred  Users to the Site. </li>
          <li>Paying Sub-Referrals. Eligible users will receive a commission equal to 5% of the  amount of commissions paid to their Referred Users for payments received from Internet users who  create new your-domain user accounts using the Referred User&rsquo;s User Referral Link. </li>
          <li>Performing User Referrals. As used herein, a  &ldquo;<strong>Referred Independent Broadcaster</strong>&rdquo; means an internet  user who creates a new user account by clicking on an existing user&rsquo;s User Referral Link and who  verifies his or her account for purposes of collecting payment by completing the Site&rsquo;s age  verification process. Eligible users will receive a one-time Fifty Dollar (USD $50.00)  commission for each of their Referred Independent Broadcasters who subsequently earns a minimum  amount that we will establish, from time to time, in our sole discretion. Studio accounts are  not eligible for model referral commissions. </li>
        </ol>
      </li>
      <p>We reserve the right to modify these amounts at any time without further notice to you.</p>
      <li>Commissions on Number of Signups; Countries and Tiers.  Certain users may be eligible for commissions based on the number of Internet users who create an   account with the Site after being referred a current your-domain user. The amount of commission will  depend upon the country in which the referred Internet user resides, as described more fully below.  As applicable, a commission of One U.S. Dollar (US $1.00) will be paid for Referred Users from a  Tier 1 country, Ten U.S. Cents (US $0.10) for Referred Users from a Tier 2 country, and One U.S.  Cent (US $0.01) for Referred Users from a Tier 3 country. We reserve the right to modify these  amounts at any time without further notice to you. No commission will be paid for a Referred User  residing in a country not found in Tier 1, Tier 2, or Tier 3 below.
        <p>The following countries have been assigned to their respective Tiers as indicated below. We reserve  the right to modify the countries belonging to each tier at any time without further notice to you.</p>
        Tier 1: Netherlands Antilles Austria Australia Belgium Canada   Switzerland Germany Denmark Finland Falkland Islands (Malvinas) Faroe   Islands France United Kingdom Guernsey Gibraltar Greenland Ireland   Iceland Jersey Japan Liechtenstein Luxembourg Netherlands Norway New   Zealand Qatar Sweden Singapore San Marino United States Minor Outlying   Islands United States United States Virgin Islands <br>
        Tier 2: United Arab Emirates Aruba Brunei Darussalam Brazil the Bahamas   Cyprus Spain Equatorial Guinea Greece Hong Kong Israel Isle of Man Italy   South Korea Kuwait Cayman Islands Macau Macao French Polynesia Puerto   Rico Portugal Slovenia British Virgin Islands <br>
        Tier 3: Antigua and Barbuda Anguilla Barbados Bahrain Cook Islands Chile   Czech Republic Estonia Guam Croatia Hungary Saint Kitts and Nevis   Lebanon Lithuania Latvia Northern Mariana Islands Malta Mexico New   Caledonia Oman Poland Russian Federation Saudi Arabia Seychelles   Slovakia Turkey Trinidad and Tobago Taiwan Uruguay Venezuela, Bolivarian   Republic of <br>
      </li>
      <li>Commission Payouts. Periods for eligible users to  accumulate commissions run from the 1st through the 15th and the 16th through the 31st day of each month.  Commission payments will be made to eligible users seven days after each period is closed. In the event  that you accumulate a commission, you will not be entitled to receive payment, nor shall the Site be liable  for any such payment, unless and until the total amount of accumulated funds associated with your account  exceeds Fifty U.S. Dollars (USD $50.00). In order to receive cash commissions, you may be required to  complete a one-time claim form, which might include submission of your legal name, a copy of your  government-issued photo identification, mailing address, birth date, telephone number, social security  number and a selection of a preferred payment method. In addition, depending on the amount of commissions  accumulated, you might be required to sign, notarize, and return an affidavit or declaration of eligibility,  a liability release, an IRS Form W-9 and provide any additional information as may be required by the Site.  Failure to provide any requested information may result in forfeiture of any unpaid commissions. We  reserve the right to charge a $10.00 payment reissue fee for replacing lost or misplaced payments that  had previously been issued; this fee is assessed at time of reissue. For Independent Broadcasters  outside of the United States who are due payments, such users may receive payment from Web Saphire  Services, Ltd. Web Saphire Services, Ltd is used exclusively for sending payments to Independent  Broadcasters outside of the United States and does not otherwise receive or process any moneys or payments. </li>
      <li>Invalid Referrals. You acknowledge and agree that you  shall not be entitled to any compensation from the Site for any referral if the Site determines or  believes, in the Site&rsquo;s sole discretion, that such referral is the result of possibly fraudulent activity  or any violation of this Agreement. </li>
    </ol>
  </li>
  <li>Billing Errors. If you believe that you have been erroneously  billed, please notify us immediately of such error. If we do not hear from you within 30 days after  such billing error first appears on any account statement, such fee will be deemed acceptable by you for all  purposes, including resolution of inquiries made by your credit card issuer. You release us from all liabilities  and claims of loss resulting from any error or discrepancy that is not reported to us within 30 days of  its publication. </li>
  <li>Severability. If any term, clause or provision hereof is held  invalid or unenforceable by a court of competent jurisdiction, such invalidity shall not affect the validity or  operation of any other term, clause or provision and such invalid term, clause or provision shall be deemed to  be severed from this Agreement. </li>
  <li>Arbitration. All Disputes (including any dispute relating to the  arbitrability of this Agreement or any provision of this Agreement or any other dispute relating to arbitration)  must be submitted to arbitration before and in accordance with the arbitration rules of the American Arbitration  Association in accordance with its commercial arbitration rules and applying the laws in effect in  Orange County, California. The term &ldquo;<strong>Dispute</strong>&rdquo; means any controversy or claim arising out of or relating to the Site or the  Services or this Agreement, or any breach thereof, including any claim that this Agreement, or any part of this  Agreement is invalid, illegal or otherwise voidable or void. <br>
    <br>
    The provisions of this Arbitration Section must be construed as independent of any other covenant or provision of  this Agreement; provided that if a court of competent jurisdiction or arbitrator determines that any such  provisions are unlawful in any way, such court or arbitrator is to modify or interpret such provisions to the  minimum extent necessary to have them comply with the law. <br>
    <br>
    Judgment upon an arbitration award may be entered in any court having competent jurisdiction and will be binding,  final and non-appealable. You and the Site hereby waive to the fullest extent permitted by law, any right to or  claim for any punitive or exemplary damages against the other and agree that in the event of a dispute between  them, each shall be limited to the recovery of any actual damages sustained by it. <br>
    <br>
    This arbitration provision is self-executing and will remain in full force and effect after the expiration or  termination of this Agreement. In the event either party fails to appear at any properly noticed arbitration  proceeding, an award may be entered against such party by default or otherwise notwithstanding said failure to  appear. <br>
    <br>
    Arbitration will take place in Orange County, California exclusively. <br>
    <br>
    You and the Site hereby agree that no action (whether for arbitration, damages, injunctive, equitable or other  relief, including rescission) will be maintained by any party to enforce any liability or obligation of the other  party, whether arising from this Agreement or otherwise, or any other Dispute, unless brought before the expiration  of the earlier of one year from the occurrence of the facts giving rise to such claims or within 90 days from  either the actual discovery of the facts giving rise to such claims or from the date on which the party should  have, in the exercise of reasonable diligence, discovered such facts. <br>
    <br>
    The obligation to arbitrate is not binding upon the Site with respect to claims relating to its trademarks, service  marks, patents, copyrights, or other intellectual-property rights, or requests for temporary restraining orders,  preliminary injunctions or other procedures in a court of competent jurisdiction to obtain interim relief when  deemed necessary by such court to preserve the status quo or prevent irreparable injury pending resolution by  arbitration of the actual dispute between the parties. <br>
    <br>
    The prevailing party will be entitled to receive from the non-prevailing party its costs relating to the arbitration  proceeding including but not limited to, the arbitrator's fees, attorneys' fees and costs, witness fees,  transcription fees, etc. and sales and use taxes thereon, if any. <br>
    <br>
    You and the Site each acknowledges and agrees that it is the intent of the parties that arbitration and litigation  between the parties will be of the parties' individual claims, and that none of their respective claims may be  arbitrated or litigated on a class-wide basis. </li>
  <li>Cancellation By User. You may cancel your membership and your  account at any time by simply sending a request to do so via our contact page. You agree to  be personally liable for any and all charges incurred by your account, username and password until you terminate  your membership as provided herein. In the event that you cancel your account, refunds may be granted for Virtual  Money that was directly purchased by you. No funds will be credited to you or will be converted to cash or other  form of reimbursement unless those funds were paid by you for the purchase of Virtual Money on our Site. Upon  our processing of your request to cancel your membership, you will no longer have access to the non-public areas  of the Service. </li>
  <li>Termination By the Site. Without limiting other remedies, the  Service may immediately issue a warning, temporarily suspend, indefinitely suspend, or terminate your access and  use of the Service and refuse to provide services to you at any time, with or without advance notice, if: (a)  the Site believes that you have breached any of these Terms and Conditions; (b) we are unable to verify or  authenticate any information you provide to us; (c) we believe that your actions may cause legal liability for  you, our users or us; or (d) the Site decides to cease operations or to otherwise discontinue any of the Site or  parts thereof. You agree that neither the Site, nor any third party acting on our behalf, shall be liable to you  for any termination of your membership or access to the Service. You agree that if your account is terminated by  us, you will not attempt to re-register as a user without prior written consent from the Site. </li>
  <li>After Termination or Cancellation. You accept that when you  cancel your membership with the Service you will be automatically locked out of the Service.  You will be   unable to access your account on the Service.  You also agree and accept that upon cancellation your account,  we have no obligation to maintain or store any mail or other membership materials and that such  information may be irretrievable. </li>
  <li>Indemnification. You agree to defend, indemnify, and hold  the Site and its affiliates, successors, assigns, officers, employees, agents, directors, shareholders and attorneys  harmless from and against any and all claims and liabilities, including reasonable attorneys&rsquo; and experts&rsquo; fees,  related to or arising from: (i) any breach by you of this Agreement; (ii) your use (or misuse) of the Service,  Site and/or Promotional Materials; (iii) all conduct and activities occurring using your account and/or Referral  Sites, if any; (iv) any item or service sold or advertised in connection with your Referral Sites, if any; (v)  any defamatory, libelous or illegal material(s) contained within your Content or your information or data; (vi)  any claim or contention that your Referral Sites, if any, contain information, data or other materials which  infringes any third party&rsquo;s patent, copyright, trademark, or other intellectual property rights or violates any  third party's rights of privacy or publicity; (vii) third-party access or use of any Promotional Materials  provided to you; (viii) any claim related to your website(s); (ix) any costs incurred on your behalf as a result  of your failure to comply with local or federal laws of the United  States; and/or (x) any violation of this Agreement. We reserve the right, at our expense, to  participate in the defense of any matter otherwise subject to indemnification from you, but shall have no  obligation to do so, and we are permitted by this Agreement to later seek indemnification from you. You shall  not settle any such claim or liability without the prior written consent of the Site. You understand that we  will take any and all measures to protect ourselves from any legal or civil litigation including, but not limited  to canceling your account, in our sole discretion. You also understand that we will charge on an hourly basis  for any and all time spent responding to any third-party complaints, disputes, copyright claims or actions  involving you or your Referral Sites. </li>
</ol>

</div>

 <div class="disclaimer">
<!--Start Zombaio Code--><script src="https://secure.zombaio.com/External/loc-scr/?63304158wb3bddf77678896c569b2a7d5aae88d89"></script><!--End Zombaio Code-->
    </div>

</body>
</html>

<?PHP
include("_main.footer.php");

?>






